name: Build and Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  windows:
    defaults:
      run:
        shell: cmd
    strategy:
      matrix:
          version: ["8.2"]
          arch: [x64]
          ts: [nts]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup PHP
        id: setup-php
        uses: cmb69/setup-php-sdk@v0.7
        with:
          version: ${{matrix.version}}
          arch: ${{matrix.arch}}
          ts: ${{matrix.ts}}
      - name: Enable Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{matrix.arch}}
          toolset: ${{steps.setup-php.outputs.toolset}}
      - name: phpize
        run: |
          cd php-ast
          phpize
          configure --with-prefix=${{steps.setup-php.outputs.prefix}}
          nmake
      - name: package
        run: |
          md binaries
          copy php-ast/LICENSE binaries
          Get-ChildItem -Recurse -Filter "php_ast.dll" | ForEach-Object {Copy-Item -Path $_.FullName -Destination "binaries"}
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: php_ast-${{matrix.php}}-x64-${{matrix.ts}}
          path: binaries